// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upwlitalfxlwwsmhukoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwd2xpdGFsZnhsd3dzbWh1a295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTUxMDIsImV4cCI6MjA3MzU5MTEwMn0.x5uaw6UCxcuGOqUr0rsXgIRS4gWIVLH37HtzNG9aSOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});